### ISSUE TITLE
Why not player's inventory ?

### ISSUE THREAD

**Issue by Miaourt** [Tfarcenim/FabricFastBench#1]
Hi, thanks for your mod, always useful to snatch some TPS 😁
Wondered why it couldn't be used to cache player's inventory crafting table ?

**Comment by Tfarcenim** [comment]
I did get it working somewhat, problem is it's not 100% bug free

**Comment by Miaourt** [comment]
Woah, great ! Thanks for your work !
What kind of bug are you encountering ?

**Comment by Tfarcenim** [comment]
seems to not be an issue anymore
