### ISSUE TITLE
Invisible items in crafting table

### ISSUE THREAD

**Issue by harvanchik** [Tfarcenim/FabricFastBench#11]
On servers, the output item in the crafting table is invisible. 

https://i.gyazo.com/dbb5d349a66e262efdd1395ea06f674a.mp4

**Comment by Tfarcenim** [comment]
The mod is required on both server and client, installing it on server only causes this, there is nothing I can do for now.

**Comment by harvanchik** [comment]
Okay.  I guess it also happens when it's on client only and not on the server.  I had it installed on client.
