### ISSUE TITLE
No 1.17.1

### ISSUE THREAD

**Issue by MenacingPerson** [Tfarcenim/FabricFastBench#13]
Is the optimisation included in 1.17?

**Comment by MagmaSlime123** [comment]
The mod's dead.

**Comment by Tfarcenim** [comment]
> The mod's dead.

Don't make up lies, there's a difference between dead, and "author is busy so stop expecting instantaneous ports on day 1."

**Comment by Tfarcenim** [comment]
1.17 is being skipped in favor of 1.18
