### ISSUE TITLE
Crafting output is invisible when using fastbench

### ISSUE THREAD

**Issue by keatit71** [Tfarcenim/FabricFastBench#16]
When using fastbench crafting in inventory or on a bench causes the output to be invisible and when this mod was removed there was no longer invisible outputs.

**Comment by Tfarcenim** [comment]
That usually means it wasn't installed on both sides.

**Comment by keatit71** [comment]
Oh I thought it would work client side like fastfurnace

**Comment by greensad** [comment]
related: https://github.com/Lizard-Of-Oz/Inventorio/issues/97

Single-player game

**Comment by Tfarcenim** [comment]
Not related at all, open a new issue for that.
