### ISSUE TITLE
Freeze when Shift-Clicking (1.16.1)

### ISSUE THREAD

**Issue by rileduphunt** [Tfarcenim/FabricFastBench#4]
Shift-clicking certain items into a crafting table (e.g. sticks, cobblestone) causes the game to freeze.

Fabric loader version 0.8.9+build.203
Fabric API Version 0.14.1+build.372-1.16
FastBench version 2.0

No error shows up in the logs, the game just hangs indefinitely.

**Comment by Tfarcenim** [comment]
this in a clean instance?

**Comment by Tfarcenim** [comment]
Fixed in 2.2
