### ISSUE TITLE
With the Stacc mod, crafting tens of millions of items at once can cause the server to freeze / crash.

### ISSUE THREAD

**Issue by James103** [Tfarcenim/FabricFastBench#6]
Minecraft 1.16.1
Stacc 1.16.1 4
FastBench 2.3
See Devan-Kerman/Stacc#6

When you craft millions of items at once, both the client and server will freeze for at least a few seconds. Attempting to craft more than a hundred million items at once can crash the server due to the watchdog.

This is because even when shift-clicking, it only performs one craft per loop (doing upwards of millions of loops at once) instead of doing it all as much as possible in a single loop.

**Comment by Tfarcenim** [comment]
not a bug in fastbench but the limits of what can be done with vanilla crafting.

**Comment by Ueaj-Kerman** [comment]
iritat

**Comment by Tfarcenim** [comment]
no, but I think I can make it faster

**Comment by Ueaj-Kerman** [comment]
did u make it faster or did u give up

**Comment by Tfarcenim** [comment]
Stacc fixed this on their end.

**Comment by Ueaj-Kerman** [comment]
Wait did I, well kinda cus I just yote the mod but idk if that counts

**Comment by Tfarcenim** [comment]
Considering this is a vanilla issue and has nothing to do with fastbench at all, I don't know why it was reported here. it's like saying a fire extinguisher can't put out an exploding fireworks factory.

**Comment by Tfarcenim** [comment]
Stack sizes in crafting table are capped to like 50k I think so this doesn't happen again

**Comment by Ueaj-Kerman** [comment]
oh right, I did do that
