### ISSUE TITLE
Result doesn't appear

### ISSUE THREAD

**Issue by Maelep** [Tfarcenim/FabricFastBench#7]
When installing on server only, crafting items in the Crafting Table doesn't show the result of the recipe.
For example, crafting sticks doesn't show the result but clicking on the result (blank) gives me the sticks.
It works if I install the mod on the client.

Minecraft 1.16.3 (Fabric) with:
- Phosphor
- Lithium
- Sodium
- Fabric Tree Chopper
- Fast Furnace
- Overworld 2
- Suitably Stackable Stew
- Villager Fix

**Comment by Tfarcenim** [comment]
It's required on both sides.  Installing it on only server will cause visual glitches.
